version: "3.8"

services:
    react_client:
        build:
            context: ./react_client
            dockerfile: Dockerfile
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - node_server
        networks:
            - network
            
    node_server:
        build:
            context: ./node_server
            dockerfile: Dockerfile
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./server:/server
            - /server/node_modules
        networks:
            - network
            
networks:
    network:
        driver: bridge